/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sige.misc;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author daveybtw
 */
public class ds_template1 extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form ds_admin_user
     */
    public ds_template1() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(100, 30);
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_menu = new javax.swing.JPanel();
        left_footer = new javax.swing.JPanel();
        left_header = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        left_options = new javax.swing.JPanel();
        registrar_usuarios = new javax.swing.JLabel();
        inicio_left = new javax.swing.JLabel();
        modificar_left = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        min_btn = new javax.swing.JLabel();
        cls_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        Cerrar_Sesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);
        setResizable(false);

        left_menu.setBackground(new java.awt.Color(50, 55, 61));
        left_menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        left_footer.setBackground(new java.awt.Color(50, 55, 61));
        left_footer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout left_footerLayout = new javax.swing.GroupLayout(left_footer);
        left_footer.setLayout(left_footerLayout);
        left_footerLayout.setHorizontalGroup(
            left_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        left_footerLayout.setVerticalGroup(
            left_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ds_ims/avatar.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ds_ims/bg_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout left_headerLayout = new javax.swing.GroupLayout(left_header);
        left_header.setLayout(left_headerLayout);
        left_headerLayout.setHorizontalGroup(
            left_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(left_headerLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        left_headerLayout.setVerticalGroup(
            left_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_headerLayout.createSequentialGroup()
                .addGroup(left_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(left_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(left_headerLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        left_options.setBackground(new java.awt.Color(50, 55, 61));

        registrar_usuarios.setForeground(new java.awt.Color(254, 254, 254));
        registrar_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar_usuarios.setText("Registrar usuarios");
        registrar_usuarios.setAlignmentX(0.6F);
        registrar_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrar_usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrar_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrar_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrar_usuariosMouseExited(evt);
            }
        });

        inicio_left.setForeground(new java.awt.Color(254, 254, 254));
        inicio_left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio_left.setText("Inicio");
        inicio_left.setAlignmentX(0.6F);
        inicio_left.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inicio_left.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inicio_left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicio_leftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicio_leftMouseExited(evt);
            }
        });

        modificar_left.setForeground(new java.awt.Color(254, 254, 254));
        modificar_left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificar_left.setText("Modificar usuarios");
        modificar_left.setAlignmentX(0.6F);
        modificar_left.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificar_left.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificar_left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificar_leftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificar_leftMouseExited(evt);
            }
        });

        javax.swing.GroupLayout left_optionsLayout = new javax.swing.GroupLayout(left_options);
        left_options.setLayout(left_optionsLayout);
        left_optionsLayout.setHorizontalGroup(
            left_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio_left, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(modificar_left, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(registrar_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        left_optionsLayout.setVerticalGroup(
            left_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_optionsLayout.createSequentialGroup()
                .addComponent(inicio_left, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(modificar_left, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(registrar_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout left_menuLayout = new javax.swing.GroupLayout(left_menu);
        left_menu.setLayout(left_menuLayout);
        left_menuLayout.setHorizontalGroup(
            left_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left_header, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(left_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(left_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        left_menuLayout.setVerticalGroup(
            left_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_menuLayout.createSequentialGroup()
                .addComponent(left_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(left_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(left_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(50, 55, 61));
        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));

        min_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ds_ims/btn_minimize.png"))); // NOI18N
        min_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min_btnMouseClicked(evt);
            }
        });

        cls_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ds_ims/btn_close.png"))); // NOI18N
        cls_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cls_btnMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SiGE");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addComponent(jLabel2)
                .addGap(459, 459, 459)
                .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cls_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cls_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        content_panel.setBackground(java.awt.Color.white);
        content_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout content_panelLayout = new javax.swing.GroupLayout(content_panel);
        content_panel.setLayout(content_panelLayout);
        content_panelLayout.setHorizontalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        content_panelLayout.setVerticalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        Cerrar_Sesion.setBackground(new java.awt.Color(254, 254, 254));
        Cerrar_Sesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cerrar_Sesion.setForeground(new java.awt.Color(254, 254, 254));
        Cerrar_Sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cerrar_Sesion.setText("Cerrar Sesion");
        Cerrar_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cerrar_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(left_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(content_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(left_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(content_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_usuariosMouseEntered
        registrar_usuarios.setOpaque(true);
        registrar_usuarios.setBackground(new Color(2, 143, 224));// TODO add your handling code here:
    }//GEN-LAST:event_registrar_usuariosMouseEntered

    private void registrar_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_usuariosMouseExited
        registrar_usuarios.setOpaque(false);
        registrar_usuarios.setBackground(new Color(50,55,61));// TODO add your handling code here:
    }//GEN-LAST:event_registrar_usuariosMouseExited

    private void inicio_leftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_leftMouseEntered
        inicio_left.setOpaque(true);
        inicio_left.setBackground(new Color(2, 143, 224));// TODO add your handling code here:
    }//GEN-LAST:event_inicio_leftMouseEntered

    private void inicio_leftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_leftMouseExited
        inicio_left.setOpaque(false);
        inicio_left.setBackground(new Color(50,55,61));// TODO add your handling code here:
    }//GEN-LAST:event_inicio_leftMouseExited

    private void modificar_leftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_leftMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_leftMouseEntered

    private void modificar_leftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_leftMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_leftMouseExited

    private void cls_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cls_btnMouseClicked
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cls_btnMouseClicked

    private void Cerrar_SesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseExited
        Cerrar_Sesion.setOpaque(false);
        Cerrar_Sesion.setBackground(new Color(50,55,61));
        // TODO add your handling code here:
    }//GEN-LAST:event_Cerrar_SesionMouseExited

    private void Cerrar_SesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseEntered

        Cerrar_Sesion.setOpaque(true);
        Cerrar_Sesion.setBackground(new Color(2, 143, 224));
    }//GEN-LAST:event_Cerrar_SesionMouseEntered

    private void Cerrar_SesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseClicked
        this.dispose();
    }//GEN-LAST:event_Cerrar_SesionMouseClicked

    private void min_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_min_btnMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ds_template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ds_template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ds_template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ds_template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ds_template1().setVisible(true);
            }
        });
    }
    
    public static class FrameDragListener extends MouseAdapter {

        private final JFrame frame;
        private Point mouseDownCompCoords = null;

        public FrameDragListener(JFrame frame) {
            this.frame = frame;
        }

        public void mouseReleased(MouseEvent e) {
            mouseDownCompCoords = null;
        }

        public void mousePressed(MouseEvent e) {
            mouseDownCompCoords = e.getPoint();
        }

        public void mouseDragged(MouseEvent e) {
            Point currCoords = e.getLocationOnScreen();
            frame.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar_Sesion;
    private javax.swing.JLabel cls_btn;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel inicio_left;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel left_footer;
    private javax.swing.JPanel left_header;
    private javax.swing.JPanel left_menu;
    private javax.swing.JPanel left_options;
    private javax.swing.JLabel min_btn;
    private javax.swing.JLabel modificar_left;
    private javax.swing.JLabel registrar_usuarios;
    // End of variables declaration//GEN-END:variables
}
